import { Button } from '../components/Button';

export function Credits({onMenu}) {
  return <div className="wrapper">
      <h1 className='text-center mt-3'>Hi, I'm Rémi.</h1>
      <div className="p-3">
        <h2>French full-stack engineer Ruby on rails / React</h2>
        <p>I am currently looking for a job. This is my React demo. Have fun with it and share it around !</p>
        <p>You can find me there :</p>
        <div className="d-flex flex-column flex-md-row justify-content-center mb-3">
          <a className='m-1 btn btn-dark' href="https://github.com/Remitdx" alt="Github" target="_blank">Github</a>
          <a className='m-1 btn btn-primary' href="https://www.linkedin.com/in/r%C3%A9mitondeux/" alt="Linkedin" target="_blank">Linkedin</a>
          <a className='m-1 btn btn-warning' href="https://remitondeux.com" alt="Porfolio" target="_blank">Portfolio</a>
        </div>
        <p>Fonts comes from Google. Images are generated by Copilot AI. Musics and sounds are from Pixabay.</p>
      </div>
      <div className="d-flex justify-content-end">
        <Button onClick={onMenu} value={"Back to landing page"} />
      </div>
    </div>
}
